Development
karthykarthick/New-York-Times pull request #1
Opened 2020-06-22 17:37 UTC by Ahmed-Benj

Hello TSE,

We hope you are doing well.

We have finished the project : POSITIONING AND FLOATING ELEMENTS.

Coul you please review our project and indicate if there are any issues that need to be fixed ?

Kind regards,

2020-06-22 18:02 UTC, christianotieno commented
## Pull Request under review by Christian Otieno (TSE)

2020-06-22 18:39 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @karthykarthick @Ahmed-Benj  :wave:
-
You have done a good job! :tada:
We, however, do have some few changes to carry out before we proceed (see review comment).
##
- Kindly take note on the differences in the two pages below and work on the suggested changes. The views are based on a desktop (large screen view).

## Top Page and main Section 

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://raw.githack.com/karthykarthick/New-York-Times/development/index.html)|
|:---:|:---:|
|![main-page](https://user-images.githubusercontent.com/22345961/85321670-b66b4480-b4cd-11ea-8307-6eb5eeea6cfe.png)|![main-page-clone](https://user-images.githubusercontent.com/22345961/85321681-bcf9bc00-b4cd-11ea-8e2f-b4139ade7ade.png)|
- From the comparison, there are some noticeable differences. Kindly, let's improve on the main image's caption's positioning. The contents below the image and it's caption including the social icon's section needs to be centrally placed. Kindly work on that.

## Inflation of Theory Section
|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://raw.githack.com/karthykarthick/New-York-Times/development/index.html)|
|:---:|:---:|
|![inflation-of-theory](https://user-images.githubusercontent.com/22345961/85322468-14e4f280-b4cf-11ea-8e82-c199d91b3500.png)|![inflation-of-theory-clone](https://user-images.githubusercontent.com/22345961/85322489-19a9a680-b4cf-11ea-926c-a87f7482701a.png)|

- Let's improve on the theory of inflation section. the contents are not well placed as they should. Let's work on that, please.

## More in Space Section
|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://raw.githack.com/karthykarthick/New-York-Times/development/index.html)|
|:---:|:---:|
|![more-in-space](https://user-images.githubusercontent.com/22345961/85322667-5d9cab80-b4cf-11ea-957b-737de0d843c1.png)|![more-in-space-clone](https://user-images.githubusercontent.com/22345961/85322683-642b2300-b4cf-11ea-9336-22461ac2b2da.png)|

- More work needs to be done in the `more in space section` 

## Footer Section
|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://raw.githack.com/karthykarthick/New-York-Times/development/index.html)|
|:---:|:---:|
|![footer](https://user-images.githubusercontent.com/22345961/85322795-8de44a00-b4cf-11ea-8a00-8400a7879e48.png)|![footer-clone](https://user-images.githubusercontent.com/22345961/85322808-92106780-b4cf-11ea-886e-824ecec946a6.png)|

- More work needs to be done in the footer section as well. Let's improve on the styling.
##

- Also, make sure that the footer should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)).


- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-22 18:46 UTC, christianotieno commented
> Hello TSE,
> 
> We hope you are doing well.
> 
> We have finished the project : POSITIONING AND FLOATING ELEMENTS.
> 
> Coul you please review our project and indicate if there are any issues that need to be fixed ?
> 
> Kind regards,

## Good job with the summary. We can always improve on it though by highlighting what we have carried out in the project's PR to guide the reviewer on what has been achieved so far. 
- We just have to pay attention to what;s being communicated and adhere to these guidelines of having a meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
- Also be sure to take care of grammar and spelling mistake in your PR and README file as well.

2020-06-22 23:52 UTC, karthykarthick commented
final changes made and corrected our errors

2020-06-23 09:26 UTC, karthykarthick commented
final changes made based on previous review

2020-06-23 17:37 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @Ahmed-Benj  and @karthykarthick! 👋 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- As was pointed out to you by the previous reviewer, there are still some differences in the layout between your clone and the original page:

- [ ] The author's name, the date, and the social media icons are not properly aligned below the image. Please compare your clone with the original page in the screenshots below and fix this.
Your clone 👇 
![Screen Shot 2020-06-23 at 7 12 01 PM](https://user-images.githubusercontent.com/48804258/85433877-6c459a00-b585-11ea-9db5-938271a35ad2.png)
The original page 👇 
![Screen Shot 2020-06-23 at 7 12 31 PM](https://user-images.githubusercontent.com/48804258/85433925-7d8ea680-b585-11ea-96db-92709bbca10f.png)

- [ ] Your clone is missing the `Editor's Picks` section. Please compare your clone with the original page and add this missing section. 
The original page 👇 
![Screen Shot 2020-06-23 at 7 14 01 PM](https://user-images.githubusercontent.com/48804258/85434038-b3338f80-b585-11ea-8cd0-48e3555ec58a.png)
Your clone 👇 
![Screen Shot 2020-06-23 at 7 14 31 PM](https://user-images.githubusercontent.com/48804258/85434076-c5153280-b585-11ea-9cea-e9a1d868e4c9.png)

- [ ] The text above the `Theory of Inflation` section should only span the width of the images.
Your clone 👇 
![Screen Shot 2020-06-23 at 7 16 52 PM](https://user-images.githubusercontent.com/48804258/85434289-19201700-b586-11ea-8837-cbca137bcc48.png)
The original page 👇 
![Screen Shot 2020-06-23 at 7 17 09 PM](https://user-images.githubusercontent.com/48804258/85434309-23421580-b586-11ea-9cf4-6a9ba2991507.png)

- [ ] In your clone, the `Theory of inflation` section is missing a heading. Please compare your clone with the original page and fix this. 
The original page 👇 
![Screen Shot 2020-06-23 at 7 17 59 PM](https://user-images.githubusercontent.com/48804258/85434378-41a81100-b586-11ea-8add-62206baf3149.png)
Your clone 👇 
![Screen Shot 2020-06-23 at 7 18 34 PM](https://user-images.githubusercontent.com/48804258/85434426-55ec0e00-b586-11ea-81da-f689d54dc5a5.png)

- [ ] When scrolling, your navigation bar is overlapping with some of the content on your screen. Please fix this.
Your clone above the `theory of inflation`👇 
![Screen Shot 2020-06-23 at 7 20 07 PM](https://user-images.githubusercontent.com/48804258/85434590-8d5aba80-b586-11ea-95d8-00b6ad313003.png)
Your clone above `most popular`👇 
![Screen Shot 2020-06-23 at 7 20 46 PM](https://user-images.githubusercontent.com/48804258/85434636-a5323e80-b586-11ea-832f-ed8364d95fe4.png)

- [ ] The `Read 615 comments` button and the social media icons right below the article are not properly aligned. Please compare your clone with the original page and fix this.
Your clone 👇 
![Screen Shot 2020-06-23 at 7 24 13 PM](https://user-images.githubusercontent.com/48804258/85434998-2093f000-b587-11ea-987d-5564e9c690ad.png)
The original page 👇 
![Uploading Screen Shot 2020-06-23 at 7.24.46 PM.png…]()

- [ ] More work needs to be done on your typography. There are several instances where the section headings are not as large as they should be or are not as bold as they are in the original page.
Your clone 👇 
![Screen Shot 2020-06-23 at 7 28 55 PM](https://user-images.githubusercontent.com/48804258/85435468-c8a9b900-b587-11ea-8a4c-0ce41d1ff0b4.png)
The original page 👇 
![Screen Shot 2020-06-23 at 7 29 58 PM](https://user-images.githubusercontent.com/48804258/85435572-ee36c280-b587-11ea-8d96-283a69e243bc.png)
Your clone 👇 
![Screen Shot 2020-06-23 at 7 30 23 PM](https://user-images.githubusercontent.com/48804258/85435597-fc84de80-b587-11ea-9b7d-cc698829eefd.png)
The original page 👇 
![Screen Shot 2020-06-23 at 7 30 46 PM](https://user-images.githubusercontent.com/48804258/85435626-09a1cd80-b588-11ea-82cf-7a29e6cf471b.png)
Your clone 👇 
![Screen Shot 2020-06-23 at 7 31 28 PM](https://user-images.githubusercontent.com/48804258/85435691-23431500-b588-11ea-98cb-9c5b3960da37.png)
The original page 👇 
![Screen Shot 2020-06-23 at 7 31 45 PM](https://user-images.githubusercontent.com/48804258/85435725-2d651380-b588-11ea-92d8-e786d9929a5d.png)
Your clone 👇 
![Screen Shot 2020-06-23 at 7 32 18 PM](https://user-images.githubusercontent.com/48804258/85435771-41107a00-b588-11ea-8e1c-96ba12d401b8.png)
The original page 👇 
![Screen Shot 2020-06-23 at 7 32 34 PM](https://user-images.githubusercontent.com/48804258/85435795-4a99e200-b588-11ea-81f2-c1613580ff1c.png)

- [ ] The footer is missing some of the content that is present on the original page and is not styled in the same way. This was pointed out to you in your first review. Please compare yours with the original and fix this. 
Your clone 👇 
![Screen Shot 2020-06-23 at 7 35 13 PM](https://user-images.githubusercontent.com/48804258/85436024-a9f7f200-b588-11ea-97e3-b14479d23ebf.png)
The original page 👇 
![Screen Shot 2020-06-23 at 7 35 41 PM](https://user-images.githubusercontent.com/48804258/85436069-baa86800-b588-11ea-935a-d7e8ad8927b4.png)

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-23 17:38 UTC, BrittanyBlake commented on style.css
> +  /* margin: 20px 0 0 114px; */
Please remove the commented code. It makes your file look untidy. If you need to review a previous version of your code, use git history.

2020-06-24 01:36 UTC, trekab requested changes
## Changes Required! :recycle: 
Hi @Ahmed-Benj and @karthykarthick! I commend your efforts on this project so far. :+1: There are some requirements to implement in order to complete this project, though. These include:
- [ ] Your navigation bar isn't filling the entire width of the viewport.
  ![Screnshot](https://github.com/trekab/images/blob/master/img/new_york_times.png?raw=true)

- [ ] The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
- [ ] The main content should generally be centered. Yours appears to be more to the left.
  ![Screenshot](https://github.com/trekab/images/blob/master/img/news_week_clone_main.png?raw=true)
- [ ] Your `More in Space and Astronomy` & `Most Popular` section:
  - Need to have some right and left margin.
  - `Most Popular` heading is misplaced.
  - `Editor's Picks` heading is missing.
  - You have unnecessary white space between both sections.
![Screenshot](https://github.com/trekab/images/blob/master/img/most_popular.png?raw=true)
- [ ] You should have a footer that has a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-06-24 16:50 UTC, karthykarthick commented
fixed issues based on the previous review

2020-06-24 17:41 UTC, karthykarthick commented
there are some issues with the resolution we don't know  how to fix it

2020-06-24 18:47 UTC, elmejdki requested changes
# Great job guys so far :clap: :clap:, your project looks good but in order to make it get approved you need to make some changes.
### status: require changes :recycle: 

### :warning:  I have seen that you didn't make the required changes by the previous TSE, please next time you have a code review make all the mentioned changes cause it takes us a lot of effort to review your code.

- Fix the header as mentioned by the previous TSE
- Fix the main content as described by the previous TSE "The main content should generally be centered. Yours appears to be more to the left."
- Fix the More in Space and Astronomy & Most Popular sections as described by the previous TSE, here is how it should look:
![image](https://user-images.githubusercontent.com/34653764/85614710-163f2800-b653-11ea-91f0-f5b5c535bef1.png)

### Please make the required changes before you request another code  review
## Happy Coding.
_If you are stuck at any point or you have questions don't hesitate to contact me on slack_

2020-06-24 20:20 UTC, karthykarthick commented
previous errors fixed
![my resolution](https://user-images.githubusercontent.com/25564718/85623555-363c0f00-b686-11ea-9c90-3483786f00d0.png)
in my resolution it is perfect

2020-06-24 22:33 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-24 22:41 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @karthykarthick and @Ahmed-Benj, congratulations on fixing the comments by the previous TSE :+1: However, I found a bug we need to fix. Kindly check the images below for a quick fix :slightly_smiling_face: 
 
![f1](https://user-images.githubusercontent.com/46388113/85634613-4e526500-b66b-11ea-8138-ab0ca8b652ff.png)
![f2](https://user-images.githubusercontent.com/46388113/85634623-56120980-b66b-11ea-800e-c02e07b87aeb.png)
![f3](https://user-images.githubusercontent.com/46388113/85634635-5ad6bd80-b66b-11ea-86de-883f2457ca31.png)
![f4](https://user-images.githubusercontent.com/46388113/85634643-62966200-b66b-11ea-8e54-5c53833678c0.png)
![f5](https://user-images.githubusercontent.com/46388113/85634656-6924d980-b66b-11ea-9c13-21eb369450c2.png)
![fc](https://user-images.githubusercontent.com/46388113/85634665-6f1aba80-b66b-11ea-8ad5-01c1893bb692.png)

Kindly address these comments and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

2020-06-24 23:16 UTC, karthykarthick commented
issues fixed based on the previous review and in my resolution, it was working perfectly 

![resolution1](https://user-images.githubusercontent.com/25564718/85636619-a48ccb80-b69e-11ea-8704-a2a623007129.png)

2020-06-24 23:50 UTC, elmejdki requested changes
# status: require changes
## sorry I can't approve this project until you fix the required changes, here is how it looks in my computer and I guess it's the same for all the previous TSE's:
![image](https://user-images.githubusercontent.com/34653764/85638391-b27e2480-b67d-11ea-8ba2-9fe84eeac507.png)

## contact when you see this comment so we can range a solution or if you were stuck I can help you out.
### Happy Coding

2020-06-25 06:49 UTC, karthykarthick commented
I
![my screen](https://user-images.githubusercontent.com/25564718/85669677-b6da2a00-b6dd-11ea-8578-7a8f1aedc710.png)
 take a screenshot from git hub pages in my system it is perfect 
previous TSE are viewing different resolution I think it causes a problem and also I attach a screenshot from GitHub pages for my resolution

2020-06-25 08:28 UTC, trekab requested changes
## Changes Required! :recycle: 
Hi @team, well done! You are almost there. There are a few fixes to make to complete this project. Check out the screenshot below. I have pointed out areas that should be fixed. Try to compare your clone to the original in the marked areas and adjust accordingly.
![screenshot](https://github.com/trekab/images/blob/master/img/new_screenshot.png?raw=true)

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-06-25 10:28 UTC, karthykarthick commented
changes made based on the previous review

2020-06-25 10:54 UTC, HADDADSOHAIB requested changes
### Status: Change required :recycle: 

### Hi everyone

### Good job with the project, it gets better and better, unfortunately some elements of the page are messed up and have to be fixed, I will attach below those sections:
- This section is overlapping over the text:
![Screenshot from 2020-06-25 11-49-09](https://user-images.githubusercontent.com/26064042/85706322-fbfc5d00-b6d9-11ea-9a88-321f315aa8ff.png)
- The video should be center with the paragraph
![Screenshot from 2020-06-25 11-50-29](https://user-images.githubusercontent.com/26064042/85706478-264e1a80-b6da-11ea-9381-d6c961a3a785.png)
- also this picture should centered
![Screenshot from 2020-06-25 11-51-37](https://user-images.githubusercontent.com/26064042/85706610-4978ca00-b6da-11ea-9f7e-4fba0dd09086.png)
- The text is overlapping over the images:
![Screenshot from 2020-06-25 11-52-31](https://user-images.githubusercontent.com/26064042/85706737-6a411f80-b6da-11ea-8f32-c0187d3ef35c.png)
 ### Once done with the change, ask for another code request.

2020-06-26 22:33 UTC, karthykarthick commented
fixed previous issues

2020-06-26 22:56 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project @karthykarthick. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job once more!
- You can now merge these changes.
- I wish you all the very best in your next tasks 👇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-06-26 23:58 UTC, merged